title: Vivian Nnaduogu
logo: WhatsApp Image 2025-05-11 at 01.42.34.jpeg
description:Highly motivated, results-oriented, and analytical Data Analyst with a strong 
foundation in extracting, cleaning, and transforming data using SQL. Experienced in performing 
comprehensive data analysis and generating actionable insights through Excel-based models and 
reports. Proven ability to develop impactful dashboards and visualizations using Power BI to 
communicate key findings effectively, identify key trends, and drive data-informed decision-making. Passionate about 
uncovering data-driven solutions and translating complex data into actionable insights.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal 
